version: "3.8"                                          # 파일 규격 버전
services:                                               # 이 항목 밑에 실행하려는 컨테이너들을 정의
  sns-redis:                        # 서비스명
    container_name: sns-redis       # 컨테이너 명
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: ksw48483/sns-redis
    ports:
      - "6379:6379"
  sns-database:
    container_name: sns-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: ksw48483/sns-database
    environment:
      - MARIADB_DATABASE=sns
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"      # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
  sns-app:
    container_name: sns-app
    build: .             # 도커 파일이 있는 위치
    depends_on:          # DB, REDIS 컨테이너가 실행된 다음 WEB을 실행시킨다.
      - sns-database
      - sns-redis
    image: ksw48483/sns-app
    environment:
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    ports:
      - "80:8080"
    restart: always