debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.example.careerting: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  profiles.active: prod
---
spring:
  config.activate.on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/sns0815
    username: swkang
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
#    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
#  sql.init.mode: always


jwt:
  secret-key: spring.project-2023.08.15.asdfgh1234!!!-spring

  # 30 days
  token.expired-time-ms: 2592000000

---
spring:
  config.activate.on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://sns-database:3306/sns?characterEncoding=UTF-8
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    redis:
      host: sns-redis
      port: 6379
  jpa:
    hibernate.ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
sns:
  base:
    url: http://52.78.154.176/dir/

jwt:
  secret-key: ${JWT_SECRET_KEY}
  # 30 days
  token.expired-time-ms: 2592000000